module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:ae4deb94948442fbe3664ed4acfa0807$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getExposureSheet()
	local s = {

		{nombre = "walk", loop = true, duracion = 125, frames = {2,3} },
		{nombre = "jump", loop = true, duracion = 50, frames = {4,5} },	
	}
	return s
end
function getSpriteSheetData()
    local sheet = {
        frames = {
			{
				name = "arabeja.png",
				spriteColorRect = { x = 0, y = 0, width = 653, height = 549 },
				textureRect = { x = 1312, y = 2, width = 653, height = 549 },
				spriteSourceSize = { width = 653, height = 549 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arabeja1.png",
				spriteColorRect = { x = 0, y = 0, width = 653, height = 573 },
				textureRect = { x = 2, y = 2, width = 653, height = 573 },
				spriteSourceSize = { width = 653, height = 573 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arabeja2.png",
				spriteColorRect = { x = 0, y = 2, width = 653, height = 571 },
				textureRect = { x = 657, y = 2, width = 653, height = 571 },
				spriteSourceSize = { width = 653, height = 573 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "arabejaSalto1.png",
				spriteColorRect = { x = 0, y = 0, width = 611, height = 573 },
				textureRect = { x = 1312, y = 553, width = 611, height = 573 },
				spriteSourceSize = { width = 611, height = 573 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arañejaSalto2.png",
				spriteColorRect = { x = 0, y = 2, width = 607, height = 566 },
				textureRect = { x = 657, y = 575, width = 607, height = 566 },
				spriteSourceSize = { width = 607, height = 568 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
    return sheet
end

