module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:ab28f28c33c9d0f4d5197ed8095fe4d0$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getExposureSheet()
	local s = {
		{nombre = "anticuerpo", loop = false, duracion = 1667, frames = {1} },
		{nombre = "globlulo", loop = false, duracion = 1667, frames = {2} },
	}
	return s
end

function getSpriteSheetData()
    local sheet = {
        frames = {
			{
				name = "Anticuerpo.png",
				spriteColorRect = { x = 0, y = 0, width = 222, height = 196 },
				textureRect = { x = 2, y = 2, width = 222, height = 196 },
				spriteSourceSize = { width = 222, height = 196 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "globulo.png",
				spriteColorRect = { x = 0, y = 0, width = 131, height = 173 },
				textureRect = { x = 2, y = 200, width = 131, height = 173 },
				spriteSourceSize = { width = 131, height = 173 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
    return sheet
end

