module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:897bd107c22ec8ff2c870d9295d052bc$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getExposureSheet()
	local s = {
		{nombre = "beat", loop = true, duracion = 1000	, frames = {2,3,4,5,6,7,5,4,3} },
	}
	return s
end


function getSpriteSheetData()
    local sheet = {
        frames = {
			{
				name = "Heart3.jpg",
				spriteColorRect = { x = 0, y = 0, width = 180, height = 156 },
				textureRect = { x = 837, y = 2, width = 180, height = 156 },
				spriteSourceSize = { width = 180, height = 156 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "corazon_bumping1_10.png",
				spriteColorRect = { x = 96, y = 68, width = 273, height = 352 },
				textureRect = { x = 554, y = 356, width = 273, height = 352 },
				spriteSourceSize = { width = 479, height = 514 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "corazon_bumping2_9.png",
				spriteColorRect = { x = 97, y = 68, width = 273, height = 352 },
				textureRect = { x = 279, y = 356, width = 273, height = 352 },
				spriteSourceSize = { width = 479, height = 514 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "corazon_bumping3_8.png",
				spriteColorRect = { x = 96, y = 68, width = 275, height = 352 },
				textureRect = { x = 2, y = 356, width = 275, height = 352 },
				spriteSourceSize = { width = 479, height = 514 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "corazon_bumping4_7.png",
				spriteColorRect = { x = 97, y = 69, width = 275, height = 352 },
				textureRect = { x = 560, y = 2, width = 275, height = 352 },
				spriteSourceSize = { width = 479, height = 514 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "corazon_bumping5.png",
				spriteColorRect = { x = 95, y = 69, width = 279, height = 352 },
				textureRect = { x = 2, y = 2, width = 279, height = 352 },
				spriteSourceSize = { width = 479, height = 514 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "corazon_bumping6.png",
				spriteColorRect = { x = 96, y = 69, width = 275, height = 352 },
				textureRect = { x = 283, y = 2, width = 275, height = 352 },
				spriteSourceSize = { width = 479, height = 514 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "corazon_pulido.png",
				spriteColorRect = { x = 549, y = 276, width = 272, height = 352 },
				textureRect = { x = 2, y = 710, width = 272, height = 352 },
				spriteSourceSize = { width = 1280, height = 760 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
    return sheet
end

