module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:a462cf3d8d292dc0c5328975aa169af2$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getExposureSheet()
	local s = {

		{nombre = "walk", loop = true, duracion = 1250, frames = {1,2,3} },

	}
	return s
end

function getSpriteSheetData()
    local sheet = {
        frames = {
			{
				name = "moco1.png",
				spriteColorRect = { x = 0, y = 0, width = 496, height = 421 },
				textureRect = { x = 1080, y = 2, width = 496, height = 421 },
				spriteSourceSize = { width = 496, height = 421 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "moco2.png",
				spriteColorRect = { x = 0, y = 0, width = 532, height = 425 },
				textureRect = { x = 2, y = 2, width = 532, height = 425 },
				spriteSourceSize = { width = 532, height = 425 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "moco3.png",
				spriteColorRect = { x = 0, y = 0, width = 542, height = 424 },
				textureRect = { x = 536, y = 2, width = 542, height = 424 },
				spriteSourceSize = { width = 542, height = 424 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mocohit solo.png",
				spriteColorRect = { x = 0, y = 0, width = 284, height = 222 },
				textureRect = { x = 1578, y = 2, width = 284, height = 222 },
				spriteSourceSize = { width = 284, height = 222 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
    return sheet
end

