module(...)

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:3c5c35ca26140be9cb5089d33a0bb668$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getExposureSheet()
	local s = {

		{nombre = "walk", loop = true, duracion = 1250, frames = {1,2,3,4,5,6} },
		{nombre = "hit", loop = false, duracion = 1667, frames = {7} },
	}
	return s
end

function getSpriteSheetData()
    local sheet = {
        frames = {
			{
				name = "PERRO1.png",
				spriteColorRect = { x = 100, y = 83, width = 798, height = 449 },
				textureRect = { x = 2, y = 824, width = 798, height = 449 },
				spriteSourceSize = { width = 1146, height = 833 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "PERRO2.png",
				spriteColorRect = { x = 91, y = 63, width = 804, height = 427 },
				textureRect = { x = 822, y = 465, width = 804, height = 427 },
				spriteSourceSize = { width = 1146, height = 833 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "PERRO3.png",
				spriteColorRect = { x = 130, y = 68, width = 760, height = 465 },
				textureRect = { x = 2, y = 1275, width = 760, height = 465 },
				spriteSourceSize = { width = 1146, height = 833 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "PERRO4.png",
				spriteColorRect = { x = 81, y = 81, width = 818, height = 413 },
				textureRect = { x = 2, y = 409, width = 818, height = 413 },
				spriteSourceSize = { width = 1146, height = 833 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "PERRO5.png",
				spriteColorRect = { x = 63, y = 74, width = 836, height = 405 },
				textureRect = { x = 2, y = 2, width = 836, height = 405 },
				spriteSourceSize = { width = 1146, height = 833 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "PERRO6.png",
				spriteColorRect = { x = 75, y = 80, width = 824, height = 461 },
				textureRect = { x = 840, y = 2, width = 824, height = 461 },
				spriteSourceSize = { width = 1146, height = 833 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "perroOUCH.png",
				spriteColorRect = { x = 0, y = 0, width = 293, height = 183 },
				textureRect = { x = 1666, y = 2, width = 293, height = 183 },
				spriteSourceSize = { width = 293, height = 183 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
    return sheet
end
